openapi: 3.0.0
info:
  title: Postgres SQL Executor
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /execute-sql:
    post:
      summary: Execute a read-only SQL query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        "200":
          description: Query result
